### ISSUE TITLE
Questions regarding simulating endpoints for camel-k routes

### ISSUE THREAD

**Issue by grebrov** [citrusframework/yaks#107]
Dear Citrus/YAKS Contributors,

thank you very much for your efforts and ideas - highly appreciated. The approach of yaks combined with the possibilities of citrus seems really promising to me. 
My potential use case is testing of camel-k routes. After reading through the documentation (citrus, citrus-simulator and yaks) I have three open points - or missing links (pls let me know if you prefer having each of them in a separate issue)
**Situation**: I have a camel-k route to test which looks like this:
```
from(fromEndpoint)
.to(toEndpoint)
```
In my case fromEndpoint is mostly an imap server or kafka and toEndpoint is database or kafka

I very much like the idea of using predefined gherkin steps in order to test my routes. And with the message steps combined with camel-k steps you provide a very powerfull pre-built solution. However these are the things where I would need some help/hints
**Questions**:
1) How do I configure the endpoint in a [gherkin message step ](https://citrusframework.org/citrus/reference/2.8.0/html/index.html#actions-send) in YAKS? Via config? Via custom steps and adding my EndpointConfig.java there?
2) In my scenario, the routes normally listen to the fromEndpoints. So I need to mock those endpoints. As far as I understand the closest to this would be citrus-simulator. But this will not work for mail and kafka, right? What would be the best approach here: Looking for/building docker images that provide these endpoints like e.g. greenmail and deploy them during test with a citrus kubernetes client?
3) the toEndpoints recieve messages from the route, which seems to be well covered by citrus and is mentiond by Christoph [here](https://github.com/apache/camel-k/issues/600):
`All outbound calls to 3rd party services can be mocked with frameworks like Citrus.`
However in the camel-k case these endpoints need to be available as service in the cluster (if I understand correctly). How could I achieve this? Again with a citrus kubernetes client?

Thanks and regards - Boris

**Comment by christophd** [comment]
Hey Boris,

thanks for the kind words and your interest in Citrus/YAKS. I will try to give answers to your questions one by one.

> 1. How do I configure the endpoint in a gherkin message step in YAKS? Via config? Via custom steps and adding my EndpointConfig.java there? 


There are different options for configuring the endpoint components in Citrus. 

### Dynamic endpoint URI
First of all you can use dynamic endpoint URI that create the endpoint components on-the-fly when the test step executes.

```gherkin
When <jms:test> sends "${body}" 
```

Where `jms:` prefix choses a JMS endpoint component and `test` would be a queue name. Here is the list of supported dynamic endpoint URIs in Citrus: https://citrusframework.org/citrus/reference/2.8.0/html/index.html#dynamic-endpoint-components

The benefit here is that you can use the dynamic endpoints without any further configuration. Downside is that you add lots of technical details (connection settings, ports, user credentials) to the BDD feature file.

### Spring bean configuration in custom extension
Citrus can load its components via Spring bean configuration. This would be something like you have mentioned with `EndpointConfig.java`. At the moment you have to add this configuration in a separate extension project. So you add the Spring bean configuration class to an extension that gets added as Maven dependency to the test.

For adding extensions as Maven dependencies you can use the YAKS upload feature where sources are built and uploaded to a Snap Minio server running in the K8s cluster. 

Here is an example for this upload feature in YAKS: https://github.com/citrusframework/yaks/blob/master/README.md#custom-steps

As an alternative you could add the custom Spring bean configuration to a github repository and add that as a jitpack.io dependency in the YAKS test project.

Here is an example how jitpack.io dependencies work:
https://github.com/citrusframework/yaks/tree/master/examples/jitpack

With all these options you also need to add an environment variable pointing to your custom Spring bean config class then.

```
yaks tests --env CITRUS_SPRING_JAVA_CONFIG=org.my.config.MyEndpointConfig
```

### Predefined steps that configure endpoints
YAKS provides some predefined steps that also support you in adding endpoint configurations to your test. For instance the JMS steps provide the connection factory settings

```gherkin
Given JMS connection factory
      | type       | org.apache.activemq.ActiveMQConnectionFactory |
      | brokerUrl  | tcp://localhost:61616 |
Given JMS destination: test
```

This will create a Citrus JMS endpoint and this will be used to send/receive messages in the following. So it should be our goal to provide such mechanisms so users are able to define the endpoints as part of the Gherkin BDD feature file. This would hide technical details such as Spring bean configuration from the end user.

### Summary

The options above need to be improved and/or simplified. There might be new ways that let the user add endpoint component configurations to the test, too. I think `Predefined steps that configure endpoints` should be our first option. But of course you can not cover everything so we need to have an easy mechanism for `Spring bean configuration in custom extensions`, too. The `Dynamic endpoint URI` may work for very simple use cases and prototyping only.

**Comment by christophd** [comment]
> 2. In my scenario, the routes normally listen to the fromEndpoints. So I need to mock those endpoints. As far as I understand the closest to this would be citrus-simulator. But this will not work for mail and kafka, right? What would be the best approach here: Looking for/building docker images that provide these endpoints like e.g. greenmail and deploy them during test with a citrus kubernetes client?

I think your test starts with sending messages to that `fromEndpoint` in order to trigger the route. In my eyes no need to have `citrus-simulator` involved here. For sending messages in your test you can use the dynamic endpoint URI feature or the predefined steps provided to exchange messages via JMS, Kafka or so in your test.

**Comment by christophd** [comment]
> 3. the toEndpoints recieve messages from the route, which seems to be well covered by citrus and is mentiond by Christoph here:
All outbound calls to 3rd party services can be mocked with frameworks like Citrus.
However in the camel-k case these endpoints need to be available as service in the cluster (if I understand correctly). How could I achieve this? Again with a citrus kubernetes client?

In YAKS the test is run as part of the K8s cluster. So the test pod could also provide services that can be used within the cluster. So the idea is to let the Camel K route call the service provided by the YAKS test pod.

Another option would be to let YAKS create new simulated services in the cluster using `citrus-simulator` or something else (e.g. [Microcks](https://microcks.io/)). The YAKS test could then verify the simulated service state and/or provide simulated response messages on-the-fly.

We need to work on those concepts in more detail.

**Comment by grebrov** [comment]
> Hey Boris,
> 
> thanks for the kind words and your interest in Citrus/YAKS. I will try to give answers to your questions one by one.
> 
> > 1. How do I configure the endpoint in a gherkin message step in YAKS? Via config? Via custom steps and adding my EndpointConfig.java there?
> 
> There are different options for configuring the endpoint components in Citrus.
> 
> ### Dynamic endpoint URI
....
> ### Spring bean configuration in custom extension
...

> ### Predefined steps that configure endpoints
...
> ### Summary
> The options above need to be improved and/or simplified. There might be new ways that let the user add endpoint component configurations to the test, too. I think `Predefined steps that configure endpoints` should be our first option. But of course you can not cover everything so we need to have an easy mechanism for `Spring bean configuration in custom extensions`, too. The `Dynamic endpoint URI` may work for very simple use cases and prototyping only.

Great and sorry for overlooking the dynamic endpoint section in your documentation. Predefined steps sounds good, but requires adding all technical elements to the feature file as well  (at least if you want to have it generic), so I don't really see an advantage (especially with the use of dynamic endpoint names).

**Comment by grebrov** [comment]
> > 1. In my scenario, the routes normally listen to the fromEndpoints. So I need to mock those endpoints. As far as I understand the closest to this would be citrus-simulator. But this will not work for mail and kafka, right? What would be the best approach here: Looking for/building docker images that provide these endpoints like e.g. greenmail and deploy them during test with a citrus kubernetes client?
> 
> I think your test starts with sending messages to that `fromEndpoint` in order to trigger the route. In my eyes no need to have `citrus-simulator` involved here. For sending messages in your test you can use the dynamic endpoint URI feature or the predefined steps provided to exchange messages via JMS, Kafka or so in your test.

Maybe I'm missing the point here. If my routes e.g. "waits" for an email message to arrive in an imap server, then this server needs to be available during testing. If I want to cover the complete test scenario I need to provide this email (or kafka) server. If I can achieve to have such a server which  provides messages that my route could consume via message steps, it would be great to have an example.
(Thanks for your quick and elaborated answers)

**Comment by christophd** [comment]
> Maybe I'm missing the point here. If my routes e.g. "waits" for an email message to arrive in an imap server, then this server needs to be available during testing. If I want to cover the complete test scenario I need to provide this email (or kafka) server. If I can achieve to have such a server which provides messages that my route could consume via message steps, it would be great to have an example.
(Thanks for your quick and elaborated answers)

Ah, I got that wrong in the first place. So this refers to a test infrastructure (message broker, imap server) that should be part of the test environment.

I think this could be done as preparation step before the YAKS test suite starts. So YAKS provides such pre/post hooks where you can run shell scripts or run shell commands in preparation to a test.

You could also think of having this as part of a CI pipeline that first prepares the test infrastructure and then triggers the YAKS tests. Not sure if we should add BDD steps for these infrastructure tasks. WDYT?

**Comment by grebrov** [comment]
CI Pipeline is a valid option too. What I like about the idea to have in the BDD is, that the infrastructure could be test-case specific. But as you probably will have one pipeline per "service", this doesn't really make a big difference. 
In general I think I would include it in BDD, if citrus could provide such infrastructure mocks (like citrus-simulator). If you use some images that you deploy on k8s, its an option and if you use cloud resources I would rather go for CI pipeline. But I'm far away from being an expert.
IMHO you can close the issue, my questions are answered. Thanks

**Comment by christophd** [comment]
ok, many thanks for your thoughts
