### ISSUE TITLE
Provide a linear execution strategy

### ISSUE THREAD

**Issue by nicolaferraro** [citrusframework/yaks#11]
To avoid issues, it may be better to avoid executing all tests in parallel and linearize their execution.

**Comment by christophd** [comment]
@nicolaferraro the scenarios in a feature file are executed sequentially by default. Do you refer to Yaks CLI running multiple feature files in parallel?

**Comment by nicolaferraro** [comment]
Yes, when you create multiple resources, they are executed in parallel currently. Which may cause issues because tests often assume there's no one else changing the system. A linear approach seems safer as first impl.

**Comment by christophd** [comment]
Linear execution of multiple features is given at the moment. Closing this one
