### ISSUE TITLE
Add Knative steps

### ISSUE THREAD

**Issue by christophd** [citrusframework/yaks#118]
We should provide steps to create/consume cloud events via Knative eventing. The user should be able to connect to the Knative eventing broker via Http in order to create event data. In addition to that we need a way to consume events. In a first version we can focus on creating an Http service via Knative serving that gets triggered by Knative eventing.

The tests should be able to send/verify cloud event data structure in version 1.0. As usual event data payloads are validated with the usual message content validation mechanisms in Citrus.

**Comment by nicolaferraro** [comment]
This would be awsome!
