### ISSUE TITLE
Creating generic resources

### ISSUE THREAD

**Issue by nicolaferraro** [citrusframework/yaks#132]
Looking back at the idea of externally configuring the environment and then run the tests with YAKS, I've noticed that I end up each time writing a lot of bash scripts to create resources and then use YAKS only to check that a pod prints a log line. Which is really not what I expected at the beginning.

I was wondering if we can take a different approach and allow creating resources e.g. in the background part of a test. With a bit of YAML you can really create complex things on Kubernetes, so this approach could help also make a test file also self-contained, which in turn will help also other IDE/Web tooling that we may be creating.

Something like:

```
Background:
  Given Kubernetes resource
  """
  kind: Xxx
  apiVersion: xxx/v1alpha1
  spec:
    data: yyy
  """
```

People would use this to create generic stuff for which we still don't have a specific DSL in YAKS. Wdyt?

**Comment by christophd** [comment]
that's a good idea!
