### ISSUE TITLE
Yaks report is skipping failures in early stage of exectuion

### ISSUE THREAD

**Issue by llowinge** [citrusframework/yaks#152]
When some test has failures in early stage eg. 
```
Progress: integration "metrics" in phase Error
Error: integration "metrics" deployment failed
Failed to run installation: 
exit status 1
```
or 

```
error: unable to recognize "source.yaml": no matches for kind "CamelSource" in version "sources.knative.dev/v1alpha1"
Failed to run installation: 
exit status 1
```

then it only prints 

```
Errors: 
[
  "exit status 1",
  "exit status 1"
]
Error: There are test failures!
```

but if we want to use 

```
yaks report -o junit
```

for general test results reporting then these are skipped, which i don't think is correct.

**Comment by christophd** [comment]
@llowinge are these errors in prepare scripts that are run via yaks-config.yaml?

**Comment by llowinge** [comment]
@christophd I think they are not. Eg. the second is from this yaks-config.yaml https://github.com/apache/camel-k/blob/master/e2e/yaks/common/knative/yaks-config.yaml

**Comment by llowinge** [comment]
@christophd any news about this issue ?

**Comment by christophd** [comment]
@llowinge working on it
