### ISSUE TITLE
Extensions example doesn't work with latest yaks version

### ISSUE THREAD

**Issue by tplevko** [citrusframework/yaks#202]
when trying to run [yaks extensions example](https://github.com/citrusframework/yaks/tree/master/examples/extension), with latest yaks version (0.2.0-SNAPSHOT), the example doesn't seem to work as expected.

Steps to reproduce:
1. install yaks
2. run: ```yaks test extension.feature```
3. see the error with missing step exception ```The step "YAKS can be extended!" is undefined. You can implement it using the snippet(s) below:```

**Comment by tplevko** [comment]
@christophd, just want to ask, is there anything else in the steps, the user has to perform? This particular example doesn't have the README, so I'm only guessing.

**Comment by christophd** [comment]
yes you need to upload the steps extension first. The upload will use a [snap](https://github.com/container-tools/snap) [Minio](https://min.io/) object storage that is automatically installed to the current namespace.

You can upload artifacts with this command:

```bash
$ yaks upload examples/extensions/steps
```

or directly as part of the test execution:

```bash
yaks test extensions.feature --upload steps
```

**Comment by christophd** [comment]
@nicolaferraro I am getting following error when uploading artifacts with Snap:

```
2020/11/27 11:40:42 log.go:70: snap/installer "level"=0 "msg"="Snap is already installed: skipping"  
Error: multiple group-version-kinds associated with type *v1.SecretList, refusing to guess at one
```

I am running locally on Minikube

**Comment by christophd** [comment]
@tplevko I have added some documentation on the extensions feature: https://citrusframework.org/yaks/reference/html/index.html#extensions

Maybe Jitpack is worth having a look because it is a good way to add custom steps.

**Comment by tplevko** [comment]
@christophd thanks for showing the direction. I'm also hitting the error you described above when trying to use the extension, so I'll have a look at Jitpack.

**Comment by christophd** [comment]
Ref https://github.com/container-tools/snap/issues/5
