### ISSUE TITLE
Camel-K integration created from KameletBinding with Knative isn't resolved as Running correctly for 0 replicas of integration

### ISSUE THREAD

**Issue by lfabriko** [citrusframework/yaks#215]
Setup:
yaks 0.2.0-202012170009, OCP 4.6, camel K 1.2.0

KameletBinding "inmem-to-log.binding.yaml": 
- source: InMemoryChannel 
- sink: Kamelet

Yaks test *.feature:
Scenario: Verify resource
    Given KameletBinding inmem-to-log is available
    Given Camel-K integration inmem-to-log is running

$ oc apply -f inmem-to-log.binding.yaml
$ oc get it
NAME            PHASE     KIT                        REPLICAS
inmem-to-log    Running   kit-bvdjr5bvaoquip03l5g0   0

After some time, number of replicas decreases from 1 to 0, then:
- step "Given KameletBinding inmem-to-log is available" passes correctly
- step "Given Camel-K integration inmem-to-log is running" keeps waiting, despite integration is in phase Running
(as it is another step in test, it blocks it till timeout).

**Comment by christophd** [comment]
The step `Given KameletBinding inmem-to-log is available` just checks for the custom resource to be present on the namespace. So it passes even if the integration is not running.

is that solving your issue?

**Comment by lfabriko** [comment]
I was puzzled by the second step: Camel-K integration is resolved as not running (- ie. the step keeps waiting), even though it is in phase Running... Is it expected..?

**Comment by christophd** [comment]
the integration must be in phase running and the number of replicas must be > 0

**Comment by christophd** [comment]
@lfabriko can we close this one?

**Comment by lfabriko** [comment]
Yes, I am ok with it.
