### ISSUE TITLE
cannot list resource "jobs" in API group "batch" in the namespace "xxxx"

### ISSUE THREAD

**Issue by tplevko** [citrusframework/yaks#221]
I'm hitting this issue in Yaks operator with the yaks version - "0.2.0-202101160039"

```
pkg/mod/k8s.io/client-go@v0.17.6/tools/cache/reflector.go:105: Failed to list *v1.Job: jobs.batch is forbidden: User "system:serviceaccount:tplevko:yaks-operator" cannot list resource "jobs" in API group "batch" in the namespace "tplevko"
```

**Comment by christophd** [comment]
The YAKS tests are now run as part of a job in Openshift (jobs appear in the OCP topology view). This requires an update of roles and permissions of the YAKS operator.

This is automatically done during install of YAKS. For existing operator installations another `yaks install` is required.

Sorry for any inconvenience.

**Comment by christophd** [comment]
@tplevko is your operator using global installation mode?

**Comment by tplevko** [comment]
@christophd no, I'm using `--global=false`, so it's only for one namespace.

**Comment by christophd** [comment]
@tplevko thanks, can you please check if a `yaks install` in that namespace with the new yaks cli binary solves the issue?

**Comment by tplevko** [comment]
@christophd seems like there was really problem in my setup - the local yaks update solved the issue. Thanks for the hint! Closing as this is not an issue.
