### ISSUE TITLE
Alluxio Proxy REST API not supported

### ISSUE THREAD

**Issue by NilsBerger** [citrusframework/yaks#248]
Hi all !

I am currently writing a simple test for alluxio were I want to create a directory via a rest request.

The request looks like this: `When send POST /api/v1/paths//nameOfDirectory/create-directory` [Documentation](https://docs.alluxio.io/os/restdoc/1.8/proxy/index.html)

If you looked closely you might notice the two slashes after paths. The seconds slash belongs to the name of the directory "/nameOfDirectory" and is required by the alluxio rest api to create a directory. Yaks unfortunately deletes multiple slashes next to each other in the url. Sending this request to alluxio always creates an INTERNAL_SERVER_ERROR because the "duplicate" slash gets deleted and therefore is invalid for alluxio Is there a workaround for this?

**Comment by christophd** [comment]
Not sure what library removes the `//`. I am not aware of any operation within YAKS to remove those. Maybe this is done by the underlying Http client implementation. I have to check.

**Comment by NilsBerger** [comment]
According to the method documentation "Adds error handling in case base request URL is not set properly and avoids duplicate path separators in concatenated URLs." it should be the method getRequestUrl(String urlOrPath) of class HttpClientSteps

**Comment by christophd** [comment]
@NilsBerger yes, but the method `getRequestUrl(String urlOrPath)` is not used when sending a POST request but only for health checks and waitForUrl steps.

**Comment by christophd** [comment]
I had a look and it seems to be the Apache HttpClient implementation that removes the double slashes as part of the URI normalization. Can you please try to use URL encoded value for `/nameOfDirectory`? I think it would be something like

`/api/v1/paths/%2FnameOfDirectory/create-directory`

**Comment by NilsBerger** [comment]
Thank you very much! The URL encoding worked!
