### ISSUE TITLE
Add install Camel-K/Knative roles command

### ISSUE THREAD

**Issue by christophd** [citrusframework/yaks#257]
YAKS supports special Camel-K and Knative steps in order to leverage the testing of those technologies. The steps require special role permissions on the Camel-K and Knative custom resources (get, create, watch, delete). 

The role permissions are automatically added to the yaks operator and viewer roles during the installation command as part of the cluster setup. The roles are only added when Camel-K and/or Knative groups are already available on the cluster. This implicitly adds the requirement to first install Camel-K **_before_** YAKS is installed on the cluster.

Otherwise YAKS will not add the required role permissions on the Camel-K custom resources.

We should add a separate role command in YAKS CLI that adds role permissions to an existing YAKS installation. Something like:

```
yaks roles --enable camel-k
yaks roles --enable knative
```

The command add the role permissions on the custom resources so tests can use the special Camel-K/Knative steps.

We could also add custom role permissions on other custom resources with:

```
yaks roles --add roles.yaml
```

The commands must be run on a user with cluster wide permissions (like the `yaks install` command)

**Comment by christophd** [comment]
@nicolaferraro WDYT?

**Comment by nicolaferraro** [comment]
> @nicolaferraro WDYT?

I think the best approach (the one also I'd take also on other projects...) is to require that YAKS is installed by a cluster admin. That way you should be able to create roles and cluster roles even on unknown resources, before they are created (asking confirmation to @astefanutti ), so you can add the knative+camel-k roles yourself at installation time (implicitly).

**Comment by astefanutti** [comment]
I agree with @nicolaferraro that installing Roles and/or ClusterRoles (depending on the install user) required for Camel K and Knative, even if these are not installed, seems the simplest solution.
