### ISSUE TITLE
Yaks does not resolve secrets

### ISSUE THREAD

**Issue by NilsBerger** [citrusframework/yaks#266]
Hi all!

I was currently trying to move my credentials into a secret, but the while running the test I ways get this exception "org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: No suitable driver found for ${database.url}"

I am not sure if it is a bug, or misunderstanding on my side, so I broke my yaks test down to the following setup and I still get the error

mysecret.properties

# Only configuration related to the "mysecret" named config
database.url=jdbc:presto://presto.***placeholder***.svc.cluster.local:8080/hive |
database.user=hive
database.password=***empty***

___
jdbc.settings.yaml

dependencies:
  - groupId: com.facebook.presto
    artifactId: presto-jdbc
    version: "0.247"

___
my-test.feature

Feature: JDBC API

  Background:
    Given Database connection
      | driver | com.facebook.presto.jdbc.PrestoDriver |
      | url       | ${database.url} |
      | username  | ${database.user} |
      | password  | ${database.password} |

  Scenario:
    When SQL query: Select * From parquet LIMIT 1
    Then verify column field1=emp1 

___
kubectl create secret generic my-secret --from-file=mysecret.properties -n=yaks-secret
kubectl label secret my-secret yaks.citrusframework.org/test=my-test -n=yaks-secret

___

Is there something wrong with my setup, or could this be a bug?

Thanks for you help!

Yaks Version: 0.3.0-202102110007

**Comment by christophd** [comment]
Hi Nils,

this is a bug in the JDBC step `Given Database connection`. The step does not replace variable placeholders properly.

Thanks for pointing to it. Will have a look and provide a fix
