### ISSUE TITLE
Yasks does not wait for the Istio sidecar

### ISSUE THREAD

**Issue by NilsBerger** [citrusframework/yaks#268]
Hi all!

We have a yaks feature that uses the presto sql driver and therefore needs to load the dependency first before it can work properly. Sometimes the sidecar needs longer than normal to boot up and the yaks tries to resolve the dependency before a connection thru the sidecar can be fully established. Therefore the yaks test fails, because it can not resolve the dependency. Should we just include a wait in a pre hook, or is this a bug?

We tested this with the newest version of Istio.

Thanks for you help!

**Comment by christophd** [comment]
Hi Nils,

Is this a sidecar of the YAKS test pod?

From your description I would not consider this as a bug. I rather think we need to find a way to properly wait for the service to be available. Maybe we can change the pattern to an init container if this is a sidecar on the YAKS pod. As an alternative the test could wait for a Http Url to return 200 OK or the test could wait for another Pod to log some specific message. WDYT?

**Comment by NilsBerger** [comment]
Hi Christoph,

Yes, I was talking about the sidecar of the YAKs test pod. I tried out the alternative that you mentioned (should have tried that out on my own) and this method works fine for my use case.

Thank for you help!
