### ISSUE TITLE
[Help] Capabilities of pre/post scripts

### ISSUE THREAD

**Issue by NilsBerger** [citrusframework/yaks#274]
Hi all!

Because of some specific use case I can not use the "citrus:randomUUID()" function to create random values in my feature file. I moved the creation of these values out of the feature file and wanted to create then in a shell script which is executed as a pre-script before the scenario. However I still need to access these created values later in my feature file. So I tried out two different approaches to pass these values to my feature-file: 

1. I am trying to write these values as variables in a properties-file, which are then loaded in a step (Given load variables file.properties) in the feature file.
2. I am trying to export these values in the script as environment variables

Both approaches however are unsuccessful, because the values file are still unchanged in the file and no new environment variables exists! Are the these approaches actually feasible?

Here is my command that I executed! "yaks test --settings file.settings.yaml  --resource file-variables.properties --resource file-setup.sh --resource resources/foo.parquet --resource file-cleanup.sh  file.feature"

I suspect that my pre-script is actually not executed at all, because I put a sleep into it and the execution of the feature-file starts immediately.

Thanks for your help!

**Comment by christophd** [comment]
Pre/post scripts are run on your local host only. The scripts that you have added as file resources are not executed on the test runtime. This is mainly for security reasons. We have had some discussions about it in #124.

You can pass environment variables to the test runtime like this:

```bash
$ yaks test sample.feature --env MY_VAR=value
```

Or as configuration in `yaks-config.yaml`

```yaml
config:
  runtime:
    env:
      - name: MY_VAR
        value: my-value
```

Another option I see is the use of secrets (property file) that you can bind to the test. The secrets are automatically added as test variables. See this [example on secret usage](https://github.com/citrusframework/yaks/tree/main/examples/secrets)

Maybe adding a custom extension would be another solution for you (see [documentation](https://citrusframework.org/yaks/reference/0.3.0/html/index.html#extensions)). You could add Cucumber before test hooks that create test variables.

**Comment by NilsBerger** [comment]
Hi Christoph

Thank you for your fast reply. The custom extension sounds like the best option for our use case!

The actual reason why I needed to be able execute a shell script in the test pod lies in these three alluxio rest calls.

streamId=$(curl -v -X POST http://alluxio-proxy.system.svc.cluster.local:39999/api/v1/paths/${ALLUXIO_FILE_PATH}/create-file)
curl -v -X POST http://alluxio-proxy.system.svc.cluster.local:39999/api/v1/streams/${streamId}/write --data-binary @"$PARQUET_FILE" -H "Content-Type: application/octet-stream"
curl -v -X POST http://alluxio-proxy.system.svc.cluster.local:39999/api/v1/streams${streamId}/close

After I created the file at the given file path I get the streamID back from alluxio as a response. With this streamID I can then upload the file content for the created file. It would be nice that one can save the response from an http step as a variable, so I can use this variable for the next http step.

**Comment by christophd** [comment]
You can actually save the response content to a test variable. Try this:

```gherkin
Then expect HTTP response body: @variable(streamId)@
And receive HTTP 200 OK
And print 'StreamId: ${streamId}'
```

This will use the `@variable()@` validation matcher to create a new variable `streamId` from the response body. This should work for plaintext response bodies.

**Comment by NilsBerger** [comment]
Hi Christoph!

Thank you for your solution! It worked fine! I was not aware that this validation matcher from the citrus framework was so tightly integrated. 

However one issue is remaining! Because to run our test we create some folder, files and also databases and tables we would like to clean then up after the scenario. Is there a way to define/annotate scenarios or steps so that they guaranteed to run, even if the scenario failed?

**Comment by christophd** [comment]
Hi Nils,

Citrus provides the concept of finally blocks that should do exactly what you describe. I have added a draft to use these finally blocks in a feature in the form of Groovy scripts. please have a look at: 

```
Scenario: Finally block
    Given $(doFinally().actions(echo('${greeting} in finally!')))
    And variable greeting is "Ciao"
```

The step above will use the pure Citrus action syntax in Groovy to add actions to the test. Notice that the variable `greeting` is defined after the finally block. It works because the finally block is run after the scenario.

You can also use multiline scripts or load the script from file resource:

```
Scenario: Finally block
   Given apply script
    """
    $(doFinally().actions(
        echo('${greeting} in finally!')
    ))
    """
    And variable greeting is "Ciao"
```

It was hard for me to find a proper BDD syntax. Especially to include this finally as "normal" step in the BDD Given-When-Then style. So I came up with the Groovy solution which works but is not perfect in terms of BDD. Maybe you have a better idea here?

**Comment by christophd** [comment]
@NilsBerger can we close this one?

**Comment by NilsBerger** [comment]
Hi Christoph!

Thank you for you help! Yes we can close this one
