### ISSUE TITLE
Pre/Post Scripts are not executed

### ISSUE THREAD

**Issue by NilsBerger** [citrusframework/yaks#309]
Hi! I am currently defining pre scripts on yaks version YAKS 0.4.0-202104200030. As already discussed in some earlier issues I know that these script are executed on my local host. Yet I struggle to execute a single script. To break the problem down I post a small example where the script is no executed.

[start.sh]

yaks test -s yaks.config.yaml hook.feature
---
[hook.feature]

Feature: Hello

  Scenario: Print hello message
    Given print 'Hello from YAKS!'
---
[yaks.config.yaml]

pre:
  - script: prehook.sh
  - run: sudo mkdir hook_directory
---

[prehook.sh]
sudo mkdir hook_directory
---

When executing this yaks test I still can not find the directory "hook_directory". Are there limits to the capabilities of these scripts?

**Comment by christophd** [comment]
The scripts are run locally as you have mentioned so I would expect the directory to be created on your local host. In case you need to create the directory inside of the test runtime POD you would need to run a custom Cucumber step as part of the test that creates the directory.

**Comment by NilsBerger** [comment]
Hi Christoph!

I figured out why the script was not executed. I had to change the filename **yaks.config.yaml** to **yaks-config.yaml**. After that change the scripts ran again. I that this is a bug because I copied the "yaks.config.yaml" straight out of your documentation -->`yaks test --settings yaks.settings.yaml camel-route.feature`

**Comment by christophd** [comment]
yeah config file needs to be `yaks-config.yaml`
