### ISSUE TITLE
Unknown variable 'default'

### ISSUE THREAD

**Issue by NilsBerger** [citrusframework/yaks#321]
Hi!

I am currently trying out your knative example and added the following line to the Background section, because I currently do not have a broker running on my cluster.

`Background:
    Given Knative event consumer timeout is 20000 ms
    Given create Knative broker default
    Given Knative broker default is running
    Given variable id is "citrus:randomNumber(4)"`

I get the following exception on the step:
 '[test-knative-eventing-c351hg2cjbf9cuksbe10-snsdn test-1]   And send Knative event                                                                                # org.citrusframework.yaks.knative.SendEventSteps.createEvent(io.cucumber.datatable.DataTable)
[test-knative-eventing-c351hg2cjbf9cuksbe10-snsdn test-1]       com.consol.citrus.exceptions.TestCaseFailedException: Unknown variable 'default'
[test-knative-eventing-c351hg2cjbf9cuksbe10-snsdn test-1]       at com.consol.citrus.DefaultTestCase.executeAction(DefaultTestCase.java:144)
[test-knative-eventing-c351hg2cjbf9cuksbe10-snsdn test-1]       at com.consol.citrus.DefaultTestCaseRunner.run(DefaultTestCaseRunner.java:125)
[test-knative-eventing-c351hg2cjbf9cuksbe10-snsdn test-1]       at org.citrusframework.yaks.knative.SendEventSteps.sendEventRequest(SendEventSteps.java:149)
[test-knative-eventing-c351hg2cjbf9cuksbe10-snsdn test-1]       at org.citrusframework.yaks.knative.SendEventSteps.createEvent(SendEventSteps.java:121)
[test-knative-eventing-c351hg2cjbf9cuksbe10-snsdn test-1]       at ✽.send Knative event(classpath:org/citrusframework/yaks/knative-eventing.feature:15)
[test-knative-eventing-c351hg2cjbf9cuksbe10-snsdn test-1] Caused by: com.consol.citrus.exceptions.CitrusRuntimeException: Unknown variable 'default''

The name of the variable "default" is the name of the namespace I run the test in.

Is this a bug or an application error from me?

**Comment by christophd** [comment]
I think the error is in another step in the feature file - probably in step "And send Knative event"

Please have a look on something like `${default}`. Is there anything like that in your in your feature file?

**Comment by NilsBerger** [comment]
Here is the whole code of the feature file

Feature: Knative eventing
  Background:
    Given Knative event consumer timeout is 20000 ms
    Given create Knative broker default
    Given Knative broker default is running
    Given variable id is "citrus:randomNumber(4)"
    Given Knative namespace default
  Scenario: Service trigger
    Given create Knative event consumer service hello-service
    Given create Knative trigger hello-service-trigger on service hello-service with filter on attributes
      | type   | service-greeting |
      | source | https://github.com/citrusframework/yaks |
    When Knative event data: {"msg": "Hello Knative!"}
    And send Knative event
      | type            | service-greeting |
      | source          | https://github.com/citrusframework/yaks |
      | subject         | hello service |
      | id              | say-hello-${id} |
    Then expect Knative event data: {"msg": "Hello Knative!"}
    And verify Knative event
      | type            | service-greeting |
      | source          | https://github.com/citrusframework/yaks |
      | subject         | hello service |
      | id              | say-hello-${id} |
  Scenario: Channel subscription
    Given create Knative channel hello-channel
    Given create Knative event consumer service hello-service
    Given subscribe service hello-service to Knative channel hello-channel
    Given create Knative trigger hello-channel-trigger on channel hello-channel with filter on attributes
      | type   | channel-greeting |
      | source | https://github.com/citrusframework/yaks |
    When Knative event data: {"msg": "Hello Knative!"}
    And send Knative event
      | type            | channel-greeting |
      | source          | https://github.com/citrusframework/yaks |
      | subject         | hello channel |
      | id              | say-hello-${id} |
    Then expect Knative event data: {"msg": "Hello Knative!"}
    And verify Knative event
      | type            | channel-greeting |
      | source          | https://github.com/citrusframework/yaks |
      | subject         | hello channel |
      | id              | say-hello-${id} |

I ran the code from a new machine and I still get the same error.

**Comment by christophd** [comment]
I probably have found the issue. It is the way the broker Url is constructed when using plain Kubernetes in https://github.com/citrusframework/yaks/blob/main/java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/KnativeSettings.java#L146

The namespace is added as variable syntax with `${%s}` which leads to the error.

Can you please try to explicitly set the `YAKS_KNATIVE_BROKER_URL` env setting in `yaks-config.yaml` to something like `http://broker-ingress.knative-eventing.svc.cluster.local/default/default`
