### ISSUE TITLE
Enable variable support for yaks-config.yaml

### ISSUE THREAD

**Issue by nhb-89** [citrusframework/yaks#351]
Hi!

It would be cool if you could create variables inside a the yaks-config.yaml.  For example for this use case below

config:
  namespace:
    name: this-is-a-namespace
    temporary: false
    autoRemove: false

pre:
  - name: Create secret
    script: prepare-secret.sh "{{ config.namespace.name }}"

So I can give the script the namespace as an argument. Or do you have another solution or idea, so that I am able to just define the namespace in all files?

**Comment by christophd** [comment]
yes `${YAKS_NAMESPACE}` gets injected to the prepare scripts. Thanks for your patience
