### ISSUE TITLE
YAKS Cli Installation for Release 0.6.0 installs 0.7.0-SNAPSHOT

### ISSUE THREAD

**Issue by k0pper** [citrusframework/yaks#355]
**OS**: Mac

I installed the YAKS CLI via the binary in GitHub for Release 0.6.0, placing it into my /usr/local/bin and after giving permissions `yaks verison` outputs 

```
$ ➤ yaks version 
YAKS 0.7.0-SNAPSHOT
```

Is this on purpose or am I understanding something not correctly?

**Comment by christophd** [comment]
Seem to be wrong. I'll have a look. Many thanks

**Comment by christophd** [comment]
as a workaround you can specify the docker image when installing YAKS

```shell
yaks install --operator-image docker.io/citrusframework/yaks:0.6.0
```
