### ISSUE TITLE
Pulling in jar dependencies to from HTTPS insecure (self-signed) Nexus

### ISSUE THREAD

**Issue by gerrym7** [citrusframework/yaks#452]
Normally in a Maven build we would get around the issue of insecure HTTPS by using the flags `-Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true`.  Is it possible to instruct the YAKS Operator to employ a similar method to pull dependencies over an insecure HTTPS connection?

**Comment by christophd** [comment]
So you are setting the custom Nexus repository in `yaks-config.yaml` right? You can try to set the Maven Wagon options in `MAVEN_OPTS` environment setting in `yaks-config` then.

**Comment by gerrym7** [comment]
Thanks, that worked! However now I need to be able to specify JVM options for executing the test code. Is there a way to specify Java runtime options in the yaks-config.yaml?  I have a requirement to override the Java assertions, and disable them for certain classes via “-da:Class” option.
