### ISSUE TITLE
yaks 0.12 image not working on amd64

### ISSUE THREAD

**Issue by Duvel** [citrusframework/yaks#454]
The image uploaded to docker hub is for arm64 and not amd64. Did something go wrong when releasing?

The error that I get:

```standard_init_linux.go:211: exec user process caused "exec format error"```

**Comment by christophd** [comment]
@Duvel yep something went wrong. I will have a look

**Comment by c14s** [comment]
Same issue here, any updates on this?

`exec /usr/bin/mvn: exec format error`

**Comment by christophd** [comment]
@Duvel @c14s could you please verify the fix with v0.12.1

**Comment by c14s** [comment]
I've downloaded [yaks-0.12.1-linux-64bit.tar.gz](https://github.com/citrusframework/yaks/releases/download/v0.12.1/yaks-0.12.1-linux-64bit.tar.gz), and re-installed yaks in my minikube environment.

But getting same error as before.

```
Events: 
	Type    Reason     Age   From               Message
	----    ------     ----  ----               -------
	Normal  Pulled     47s   kubelet            Container image "docker.io/citrusframework/yaks:0.12.1" already present on machine
	Normal  Created    47s   kubelet            Created container test
	Normal  Started    47s   kubelet            Started container test

 Containers:
 	test: 
 		Image:    docker.io/citrusframework/yaks:0.12.1
 		State:    Terminated
 		Reason:   Error
 		Message:  exec /usr/bin/mvn: exec format error
```

**Comment by Duvel** [comment]
On the page on docker hub it still shows as an arm image:

https://hub.docker.com/r/citrusframework/yaks/tags

@christophd is there a ci in place, that builds the image? Maybe it has switched to arm as build nodes.

**Comment by christophd** [comment]
@Duvel @c14s thank you for trying out. Just released v0.12.2 and it looks promising. Could you please give it another try? Many thanks

**Comment by c14s** [comment]
Downloaded and installed [yaks-0.12.2-linux-64bit.tar.gz](https://github.com/citrusframework/yaks/releases/download/v0.12.2/yaks-0.12.2-linux-64bit.tar.gz).

Re-test was successful now.
Thanks for the quick fix!

```
	Type    Reason     Age   From               Message
	----    ------     ----  ----               -------
	Normal  Pulled     108s  kubelet            Container image "docker.io/citrusframework/yaks:0.12.2" already present on machine
	Normal  Created    108s  kubelet            Created container test
	Normal  Started    108s  kubelet            Started container test

Containers:
	test:
		Image:         docker.io/citrusframework/yaks:0.12.2
		State:         Terminated
			Reason:       Completed
			Exit Code:    0
			Started:      Tue, 10 Jan 2023 20:26:07 +0100
			Finished:     Tue, 10 Jan 2023 20:26:29 +0100
```

**Comment by Duvel** [comment]
@christophd Yup, version 0.12.2 works for me!
