### ISSUE TITLE
YAKS fails due to inability to retrieve surefire-junit4-2.22.2

### ISSUE THREAD

**Issue by gerrym7** [citrusframework/yaks#477]
Direct access to external public repositories is forbidden in our restrictive environment and access to external artifacts can only be accessed through proxied repositories in our private Artifactory.  I made an attempt to include an entry in the yaks-config.yaml that points to our Artifactory with the appropriate proxied repository, yet YAKS continues its attempt to retrieve the JUnit Runner directly from the external central (https://repo.maven.apache.org/maven2).

This is currently a blocker for us as it's extremely unlikely our organization will make a firewall exception to get around this issue. Is there a way around this?

**Comment by christophd** [comment]
`surefire-junit4` is a Maven plugin and therefore the Maven project configuration must add a custom pluginRepository. At the moment YAKS is only able to set custom arbitrary repositories for resolving dependency artifacts.

I think this would be a good enhancement to also set custom plugin repositories for Maven.
