### ISSUE TITLE
yaks install not able to install yaks on cluster

### ISSUE THREAD

**Issue by RitikaLaddha** [citrusframework/yaks#497]
Error:
$ yaks install
OLM is available in the cluster
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x50 pc=0x262859a]

goroutine 1 [running]:
github.com/citrusframework/yaks/pkg/util/olm.maybeSetEnvVars(0xc00047bc00, {0xc0
00148c50?, 0x2d09058?, 0x4?})
        github.com/citrusframework/yaks/pkg/util/olm/operator.go:213 +0x5a
github.com/citrusframework/yaks/pkg/util/olm.Install({0x30778a8, 0xc000365590},
{0x309c8f0?, 0xc000a03080?}, {0xc00012cf58?, 0x8}, 0x1, {{0x2d15d47, 0xd}, {0x2d
09058, ...}, ...}, ...)
        github.com/citrusframework/yaks/pkg/util/olm/operator.go:169 +0x458
github.com/citrusframework/yaks/pkg/cmd.(*installCmdOptions).install(0xc0003a800
0, 0x0?, {0x0?, 0x0?, 0x0?})
        github.com/citrusframework/yaks/pkg/cmd/install.go:139 +0x4c5
github.com/citrusframework/yaks/pkg/cmd.newCmdInstall.func1(0xc0001c7c00?, {0x42
4cee0?, 0x4?, 0x2d09164?})
        github.com/citrusframework/yaks/pkg/cmd/install.go:47 +0x2f
github.com/spf13/cobra.(*Command).execute(0xc0003a6300, {0x424cee0, 0x0, 0x0})
        github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0xc000394300)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0x30778a8?)
        github.com/spf13/cobra@v1.8.0/command.go:1039 +0x13
main.main()
        ./main.go:37 +0x65

**Comment by christophd** [comment]
many thanks for reporting. Let me have a look. At the moment I have no idea why this error is happening for you.

**Comment by RitikaLaddha** [comment]
This issue is same as [issue 489](https://github.com/citrusframework/yaks/issues/489). Only difference is, I am using Azure Kubernetes service. 

This resolved my problem: [ans](https://github.com/citrusframework/yaks/issues/489#issuecomment-1842409251)

Hence closing this issue.
