### ISSUE TITLE
Test suite composition blocks

### ISSUE THREAD

**Issue by nicolaferraro** [citrusframework/yaks#55]
I was discussing with @bouskaJ about strategies that can be used to build a test suite with YAKS. For simple cases, it's enough to delegate to a pipeline the creation of an environment, then execute the YAKS tests and report status. But for more complicated scenarios we should add some hooks to allow people to execute some pre/post steps before running the tests.

I was thinking to create a concept of test group. The group is materialized into a directory on the fs.

When running the group (directory), yaks executes tests for all feature files present in the directory.

But the group can also have a `yaks-config.yaml` file, with a structure that we can define.
An example of file can be (I'm borrowing something from Github actions):

yaks-config.yaml
```
config:
  some-general-config: tbd
pre:
- script: ../prepare.sh
- run: |
    kamel version

    kamel install
    kamel run xxx.groovy
post:
- run: echo "Hello!"
```

This is enough generic to plug whatever we want to use as install mechanism for resource, including helm or operator hub.

Aside from that, we can also have additional options in the config yaml. Like:
- an option to run it in a temporary namespace
- an option to execute all child groups (subdir) defined in a group

With these building blocks, we can allow creating a whole test suite. Even converting most of the Camel K e2e tests to use yaks.

Wdyt @christophd ?

**Comment by christophd** [comment]
Awesome!
