### ISSUE TITLE
Add possibility to run all tests in a directory

### ISSUE THREAD

**Issue by nicolaferraro** [citrusframework/yaks#57]
Part of #55 

When doing `yaks test file.feature`, yaks now runs a single test (even with multiple scenarios) and prints the result. Exit code is 0 or 1 depending on the result.

When running `yaks test dir`, yaks should lookup all `.feature` files in the directory and execute the test. No matter if a single test fails, it should proceed with the others. Execution (for now) can be linear: one test after another.
When all tests are finished, it should print the result of each test. Exit code should be 1 if at least a test failed, 0 otherwise.

**Comment by bouskaJ** [comment]
This should be done. I don't have permission to close this issue. @nicolaferraro @christophd could you do that?

**Comment by christophd** [comment]
yep, thanks!
