### ISSUE TITLE
Operation cannot be fulfilled he object has been modified

### ISSUE THREAD

**Issue by bouskaJ** [citrusframework/yaks#74]
I am getting this error while rerunning the test.

1) I have the failed test:

```
----------------------------FAILED TEST -------------
Test suite results:
        test/UserReport.feature: Test Failed
```

2) Then I want to rerun - getting this error
```
➜  camel-k-example-event-streaming git:(add_tests) ✗ yaks test test/UserReport.feature
Test suite results:
        test/UserReport.feature: Operation cannot be fulfilled on tests.org.citrusframework.yaks "user-report": the object has been modified; please apply your changes to the latest version and try again
```

3) Try to rerun again - working
```
➜  camel-k-example-event-streaming git:(add_tests) ✗ yaks test test/UserReport.feature
test "user-report" updated
----------------------------CONTINUE AS EXPECTED -------------
```

**Comment by christophd** [comment]
I can not reproduce this on my side with the examples that I have. Maybe this is something specific to your test?

**Comment by bouskaJ** [comment]
I don't think so. It occurs only from time to time. I will try to investigate it and provide more details.

**Comment by christophd** [comment]
I saw this only when running tests right after the yaks operator pod has been recreated. Maybe the operator is not ready to handle events at that time and we have to wait some more seconds before running a test

**Comment by grebrov** [comment]
I can confirm the observation form bouskaJ. And in addition I can report, that sometimes the test execution is repeated twice (which I suppose to be related to this issue). 
Here is my sample test and attached the log, where you can see, that the test gets executed twice (I ran everything with version 0.0.45 client and operator
```

Feature: simple http post step
  Background:
    Given URL: https://postman-echo.com


  Scenario: Get a result from postman
    Given HTTP request body
    """
    {
      "This is a simple text"
    }
    """
    When send POST /post
    Then receive HTTP 200 OK
[post.log](https://github.com/citrusframework/yaks/files/4668291/post.log)

```

**Comment by grebrov** [comment]
Looks like this behavior occurs when you change something in the feature definition. 
To reproduce: 
1. run the above feature
2. change "This is a simple text" to "This is a changed text"
3. re-run --> Operation cannot be fulfilled on tests.org.citrusframework.yaks "<feature name>": the object has been modified; please apply your changes to the latest version and try again
