### ISSUE TITLE
Adding support for Jitpack

### ISSUE THREAD

**Issue by nicolaferraro** [citrusframework/yaks#82]
I've recently learned about Jitpack, which provides a handy way to use binary snapshots by directly referencing sources stored on Github.

I think that can provide a way to reference custom steps and glue code without having to start a Minio as we do now. We can still keep the minio approach for local development.

Wdyt?

**Comment by christophd** [comment]
+1

I had a quick look at Jitpack. Looks great and would be a good way for us to include custom steps with versioning.
