### ISSUE TITLE
Add support for environment variable in feature file

### ISSUE THREAD

**Issue by bouskaJ** [citrusframework/yaks#90]
I would like to have support for the environment variables in feature file:

1) propagate YAKS_NAMESPACE var to the running pod (we can reuse https://github.com/citrusframework/yaks/blob/master/pkg/cmd/test.go#L101)
Example:
```
Scenario:
  Given URL: http://user-report-system.${YAKS_NAMESPACE}.svc.cluster.local
  .....
```

2) support custom properties:
```
Scenario:
  Given URL: http://user-report-system.${CLUSTER_WILDCARD_DOMAIN}
  .....
```
Yaks command:
```
yaks test mytest.feature -e CLUSTER_WILDCARD_DOMAIN=apps.myocp.com
```

**Comment by bouskaJ** [comment]
@nicolaferraro @christophd WDYT?

**Comment by nicolaferraro** [comment]
Sounds good. It's usually a common practice to inject the "NAMESPACE" env var into the test, we can inject also both.

Is the cluster wildcard domain always ns.svc.cluster.local or it can be changed? It has never been clear to me.

**Comment by bouskaJ** [comment]
@nicolaferraro For cluster local addresses it should be always `ns.svc.cluster.local ` but sometimes it can be useful to have an option for custom env var injection. I tried to demonstrate it on an external address verification. We can't avoid using `CLUSTER_WILDCARD_DOMAIN` for external addresses.

**Comment by bouskaJ** [comment]
@christophd Can Citrus work ENV vars?

**Comment by christophd** [comment]
@bouskaJ yes that is pretty easy to accomplish in Citrus. I will take care of it
